server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    dashscope:
      api-key:  # 你的 DashScope API Key  测试环境直接配置在yml中
      options:
        model: qwen3.5-plus
        temperature: 0.7
        max-tokens: 2000
        top-p: 0.9

molgenie:
  kb:
    milvus:
      host:
      port: 19530
      database: default
      collection: molgenie_kb_v2
      fingerprintBits: 1024
    embedding:
      baseUrl: https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings
      model: text-embedding-v4
      dimensions: 1024

